version: "3.8"
services:
  redis_migration:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redislabs/rejson:latest
    container_name: redis
    ports:
      - "6379:6379"

  api-internal:
    build:
      context: ./redis_api
      dockerfile: Dockerfile
    container_name: api
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - redis_migration

  api-external:
    build:
      context: ./redis_api
      dockerfile: Dockerfile
    container_name: api
    environment:
      - REDIS_HOST=redis
    ports:
      - "80:5000"
    depends_on:
      - redis
      - redis_migration
      - api-internal

  ui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ui
    environment:
      - PORT=3000       # gastby develop defaults to 8000
      - GATSBY_API_HOST=api
      - GATSBY_API_PORT=5000
    ports:
      - "3000:3000"
    depends_on:
      - api-internal
