version: '3'
services:
  data_pipeline:
    build:
      context: ./data_pipeline
      dockerfile: Dockerfile
      args:
        - UID=${UID}
        - USER=${USER}
        - GID=${GID}
        - GROUP=${GROUP}
    container_name: data
    user: $USER
    environment:
      - HEADLESS=${HEADLESS}
    command: python ./scraper/scraper.py
    volumes:
      - .:/app
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ui
    command: gatsby develop -H 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
#    depends_on:
#      - data_pipeline
  redis:
    image: redis