version: "3"
services:
  redis_dev:
    image: redislabs/rejson:latest
    container_name: redis
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      - FLASK_APP=api
      - PYTHONPATH=.
      - REDIS_HOST=redis
      - REDIS_API_PORT=6379
    ports:
      - "5000:5000"
    command: python -m flask run --host=0.0.0.0
    depends_on:
      - redis_dev
